config_version = "2.0"
configuration = []

[info]
name = "{{{ APP_NAME }}}"
description = "This is a generated description. Replace it with your own."

[runtime]
application = "app.py#ExampleApplication"
workdir = "/app"

[runtime.runs_on]
type = "image"
name = "ghcr.io/luxonis/robothub-app-v2:2023.039.2206-regular"
